#name: challenge-steps-processor
#
#services:
#  kafka:
#    user: root
#    image: apache/kafka:3.8.1
#    container_name: kafka-broker
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,DOCKER://:9094
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://:9094
#      KAFKA_LOG_DIRS: /kafka/data
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_PROCESS_ROLES: broker,controller
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
#    volumes:
#      - kafka-data:/kafka/data
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:v0.7.2
#    container_name: kafka-ui
#    ports:
#      - "8080:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local-cluster
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
#    depends_on:
#      - kafka
#
#volumes:
#  kafka-data:
#    name: kafka-data



name: challenge-steps-processor

services:
  kafka:
    image: bitnami/kafka:3.8.1
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,DOCKER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://:9094
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
    volumes:
      - kafka-data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9094
    depends_on:
      - kafka

volumes:
  kafka-data:
    name: kafka-data
